### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by andypiper** [danieldevine/bird-elephant#1]
Hi there! Andy here, from Twitter Developer Relations.

Thanks for building on the v2 API, it's exciting to see new libraries emerging.

A couple of notes that may help:
- on our developer forums, we have a dedicated category for [announcement and discussion around SDKs and libraries](https://twittercommunity.com/c/libraries-and-sdks/63), and another one [specifically around the v2 API](https://twittercommunity.com/c/twitter-api/twitter-api-v2/65).
  - let us know when you feel like your library is in a state where you'd be ok with having it listed on our Tools & Libraries page on the developer website 
- feel free to borrow one of our [API version badges for your README](https://gist.github.com/andypiper/6f41242e422235fbae6e68bcce18976e), if you like!

Thanks again.

**Comment by andypiper** [comment]
Oh, and one more thing - I love the name (PHP Elephant + Twitter bird, I geddit 👍🏻 ) - we actually have an [Open Source project of our own with the same name](https://github.com/twitter/elephant-bird/), which is nothing to do with PHP at all. Could be confusing, up to you 🙂

**Comment by danieldevine** [comment]
Hi Andy, 

Thanks for looking in. Will be a while before this is ready to be listed, but I'll be sure to check in when it is.
Shame about the name - will look into alternatives :)

**Comment by danieldevine** [comment]
Nearly a full year on and a new name has been found...
