### ISSUE TITLE
Upload image issue

### ISSUE THREAD

**Issue by nerocil** [danieldevine/bird-elephant#12]
I try to upload image got this error!

`Return value of Coderjerk\BirdElephant\Request::uploadMedia() must be an instance of Coderjerk\BirdElephant\mixed, instance of GuzzleHttp\Exception\ClientException returned`

how to handle this error?

**Comment by danieldevine** [comment]
Hi @nerocil , I've removed the return type of mixed from this method, please update and try again. You should now be able to handle the error in your code.

**Comment by nerocil** [comment]
Thank you for quick reply 
After update now it throw `Undefined property: GuzzleHttp\Exception\ClientException::$media_id_string`
I use api v2 could

**Comment by nerocil** [comment]
@danieldevine sorry, the problem was at my twitter developer account after change to ELEVATED now work fine. thank you

**Comment by danieldevine** [comment]
It looks like the library is doing what it should do here, unless I misunderstand you.

Your image upload has failed, and it has thrown an exception (```GuzzleHttp\Exception\ClientException```), therefore you cannot add the image to your tweet. In your own code you need to handle the exception when you are using the upload method. For example:

```php
try {
    $image = $twitter->tweets()->upload('./img/chris.png');
} catch (\Throwable $th) {
    //https://www.php.net/manual/en/class.exception.php
    echo $th->getMessage();
    echo $th->getCode();
    echo $th->getFile();
    echo $th->getLine();
}
```

I'm closing this now as I don't believe that it's an issue with the library, but feel free to open a new issue if I've misunderstood you. Make sure you use the (updated) issue template to help me to understand.

**Comment by danieldevine** [comment]
> @danieldevine sorry, the problem was at my twitter developer account after change to ELEVATED now work fine. thank you

ah, that makes sense. No problem.
