### ISSUE TITLE
Trending Pages

### ISSUE THREAD

**Issue by VirendraArekar** [danieldevine/bird-elephant#14]
Sir i am trying to fetch all trending topic, and also trending topic by country, by country state  so i read all your document. But i didn't found any function to get data like that. so please guide me to achieve my goal to use this package.

**Comment by danieldevine** [comment]
Trends are not part of the Twitter API v2. Twitter seem to be planning to include them future: See this tweet: https://twitter.com/TwitterDev/status/1437434222633967618?s=20

In the meantime, trends are supported by Api v1.1, you can use any of the available libraries that support the old version of the API.

https://developer.twitter.com/en/search-results?limit=10&offset=0&q=trends&sort=relevance

As stated in the README.md of this package, Bird Elephant only supports Twitter API v2 endpoints. I will include support for all new endpoints as and  when they become available in the future.

**Comment by danieldevine** [comment]
I'll leave this open for now until trends are supported by Twitter API V2
