### ISSUE TITLE
I can't upload a tweet with media image

### ISSUE THREAD

**Issue by johnarleycano** [danieldevine/bird-elephant#15]
**Describe the bug**
I have upload an image, but there are not media_id_string value

**To Reproduce**
`
$twitter = new \Coderjerk\BirdElephant\BirdElephant($credentials);

$image = $twitter->tweets()->upload('img/habilitada.gif');

$media = (new \Coderjerk\BirdElephant\Compose\Media)->mediaIds([$image->media_id_string]);

$tweet = (new \Coderjerk\BirdElephant\Compose\Tweet)->text('Mensaje con imagen: @johnarleycano')
    ->media($media);`

**Screenshots**

**Environment (please complete the following information):**
 - PHP 7

**Additional context**
_Notice: Undefined property: GuzzleHttp\Exception\ClientException::$media_id_string in_

**Comment by danieldevine** [comment]
What is the value of $image when you var_dump it?

**Comment by danieldevine** [comment]
As you can see from the notice, when you have tried to upload the image, the library has thrown an exception (GuzzleHttp\Exception\ClientException). You should examine the exception to understand what is happening with your implementation.

See https://github.com/danieldevine/bird-elephant/issues/12#issuecomment-980505043
