### ISSUE TITLE
Query user list tweets

### ISSUE THREAD

**Issue by Semirsmajlovic** [danieldevine/bird-elephant#19]
I couldn't find this anywhere in the documentation and/or find the corresponding endpoint, but I would like to grab the users list(s) and output tweets.

Endpoint: https://developer.twitter.com/en/docs/twitter-api/lists/list-tweets/introduction

Is there a way to grab the tweets from a list?

**Comment by danieldevine** [comment]
Thanks for pointing this out. This can now be

**Comment by Semirsmajlovic** [comment]
Just tested it out - Worked perfectly! Thanks for the quick fix and I can go ahead and implement this today.
