### ISSUE TITLE
Lists max_results returns inaccurate count

### ISSUE THREAD

**Issue by Semirsmajlovic** [danieldevine/bird-elephant#21]
**Describe the bug**
When calling `$client->lists()->tweets()->lookup()` method with the `max_results` param, it returns an inaccurate amount of tweets, it seems that the `max_results` parameter doesn't account for the correct amount of tweets. When calling the `$user->tweets($params);` call with `max_results`, it works just fine.

**To Reproduce**
Use the following call:  

```
            $params = [
                'expansions' => 'author_id,attachments.media_keys',
                'max_results' => 7,
                'tweet.fields' => 'attachments,author_id,context_annotations,created_at,entities,reply_settings,source,text,withheld,referenced_tweets',
                'user.fields' => 'created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,url,username,verified,withheld'
            ];
            $tweets = $client->lists()->tweets()->lookup($list_id, $params);
```

**Expected behavior**
When inputting the max_results param to 7, I'd expect to see 7 tweets, but for some odd reason, it keeps returning less, when max_results isn't passed in, it returns all 100 by default.

**Screenshots**
https://i.ibb.co/BKgP7xH/Screen-Shot-2022-02-09-at-9-18-25-AM.png

**Environment (please complete the following information):**
 - Operating System Mac Big Sur
 - php version: 8.0
 - Bird Elephant version: 0.4.3

**Comment by danieldevine** [comment]
Hi @Semirsmajlovic ,

Thanks for the report, I'll look into this. To assist in debugging this, can you try with 11 as your max value and see if that gives the expected result?

**Comment by Semirsmajlovic** [comment]
Sure thing, hope this all helps! @danieldevine 

When calling the regular profile tweets, I get all 11 tweets with `max_results` passed as 11.
https://i.ibb.co/XX5V9LJ/Screen-Shot-2022-02-09-at-11-54-01-AM.png

When calling the tweets for a list, I get 8 tweets back with `max_results` passed as 11.
https://i.ibb.co/DbxPV5J/Screen-Shot-2022-02-09-at-11-48-41-AM.png

Let me know if further debugging is needed.

**Comment by Semirsmajlovic** [comment]
Thanks for looking in to this @danieldevine, so I was able to pass in a hardcoded 7 and I got 7 tweets back as well.

When I pass in 50 as the max_results, I get a return of 45 only, could there be specifics on what tweets get returned and aren't being accounted for in the array based on possibly params?

**Comment by danieldevine** [comment]
Ok, I'm finally able to reproduce - the same code as above returns 48 results when I request 50 and 93 when I request 100.  i'll take a closer look now.

**Comment by danieldevine** [comment]
@Semirsmajlovic OK, I've checked out this list on Postman, and am getting the same result - when I request 50 it returns 48.  So conclusively this in't the library., it's the API. 

I've tried a bunch of other lists and have seen  similar results. The only common factor I've seen is that the lists that returned fewer tweets than specified all included tweets that were in non-English languages, and included special characters. 

I'm afraid I can't help much more on this. Might be worth filing a bug report on the Twitter developers forum?

**Comment by Semirsmajlovic** [comment]
Thanks for your dedication on this @danieldevine, I just tested both endpoints via Postman and I am also getting inconsistent results before using the library (Should have tested this before reaching out to you), but I opened up a ticket with Twitter.

Much appreciated on looking into this! Library works smoothly.
