### ISSUE TITLE
Real life exemple

### ISSUE THREAD

**Issue by agenceKanvas** [danieldevine/bird-elephant#22]
Hi !
I'm trying to implement the lib with my php app. 
IT's a very basic one, using cron to automatically share my posts. 
I have my credentials and my API, but I can't make the link between the credentials needed. 
What I have : 
- API key 
- API secret key
- Bearer Token
- Access token 
- Access secret token

What is needed by elephant is : 
- bearer_token (so I have) 
- consumer_key : Is that the api key ?
- consumer_secret : so it's the secret key ?
- token_identifier : I assume this is the access token
- token_secret : I assume this is the access secret token 

Thanks :) And sorry for the dumb quesiton ...

**Comment by danieldevine** [comment]
Hi @agenceKanvas 

consumer_key/consumer_secret is the API key/secret - listed under 'consumer keys' in the dev portal.

token_identifier/token_secret  are the 'Access Token and Secret' 

Bearer token is the bearer token of course :)
