### ISSUE TITLE
Can a video be uploaded and attached to tweets? 

### ISSUE THREAD

**Issue by WaelMz** [danieldevine/bird-elephant#24]
Can a video be uploaded and attached to tweets? Via
`$twitter->tweets()->upload ('./img/video.mp4');`
Or any other ways to achieve this?

**Comment by danieldevine** [comment]
At the moment media uploads aren't supported through the  Twitter API v2, so this library uses v1.1 to upload the media (the only place where I use it).  The implementation is only tested on single image uploads and I haven't gone any deeper as my preference is to wait for support in APIv2, [which looks likely to happen](https://trello.com/c/Zr9zDrJx), before writing a lot of code that will be obsolete soon.

Uploading video using the old API requires a more complex approach than a simple image upload:
https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-init

Nevertheless, this could be worth implementing as its obviously a useful feature, and I'd be happy to accept a pull request.

**Comment by WaelMz** [comment]
thank you for response .
