### ISSUE TITLE
user lookup improvement

### ISSUE THREAD

**Issue by WaelMz** [danieldevine/bird-elephant#25]
**Describe the bug**
when use user lookup with invalid username return
Undefined property: stdClass::$data from function getUserIdFromUsername

**To Reproduce**
` $look = $users->lookup(['waelmahmoude111'], [
            'user.fields' => 'public_metrics',
   ]);`

**Expected behavior**
return user or (null || exception )
**Screenshots**
![image](https://user-images.githubusercontent.com/33140498/160627581-28037d25-7c53-4b7c-8eaf-b63e60448cbd.png)

**Environment (please complete the following information):**
 - windows
 - 7.4
 - "coderjerk/bird-elephant": "^0.4.3",

**Comment by danieldevine** [comment]
Hi @WaelMz,

Thanks for the report. When I try to reproduce with your code above I receive the expected result:

```php
object(stdClass)#47 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#49 (7) {
      ["value"]=>
      string(15) "waelmahmoude111"
      ["detail"]=>
      string(54) "Could not find user with usernames: [waelmahmoude111]."
      ["title"]=>
      string(15) "Not Found Error"
      ["resource_type"]=>
      string(4) "user"
      ["parameter"]=>
      string(9) "usernames"
      ["resource_id"]=>
      string(15) "waelmahmoude111"
      ["type"]=>
      string(53) "https://api.twitter.com/2/problems/resource-not-found"
    }
  }
}
```
So there must be another factor at play. Have you been able to use any other methods in the library successfully?

**Comment by danieldevine** [comment]
I'm going to close this for now, feel free to re-open if you still have an issue.
