### ISSUE TITLE
How to get complete text (tweet) using tweet id ?  

### ISSUE THREAD

**Issue by nimikkiko0** [danieldevine/bird-elephant#41]
Please help ... Soon i ll be sponsoring this project 
```
print_r($tweets->get('1554443467065118725'));


```
above request is returning me truncated tweet ?

**Comment by danieldevine** [comment]
Hi @nimikkiko0,

I ran the above and it returned the following: 

```php
^ {#52 ▼
  +"data": {#54 ▼
    +"id": "1554443467065118725"
    +"text": """
      Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.
      -Robert Frost
      Via Wise Life Lesson  https://t.co/FeEg2MfkQx
      #quotes
      #inspiration https://t.co/AhHP8rUdGQ
      """
  }
```
when I view the same tweet on Twitter it has the same content.

![image](https://user-images.githubusercontent.com/5939939/182955806-7ebb0030-c8fa-48af-8322-086ac96b3899.png)


Looks like the whole tweet to me? What result are you getting?

**Comment by danieldevine** [comment]
I'm going to close this now as there is no issue here. Feel free to reopen if I've misunderstood something.
