### ISSUE TITLE
Please add option to send Direct messages to the users

### ISSUE THREAD

**Issue by kalaiselvan162** [danieldevine/bird-elephant#49]
Right now there is no option to send direct messages via Twitter API using bird-elephant. If you could add this option to send direct messages that would be helpful for the users.

**Comment by danieldevine** [comment]
Thanks for flagging. This was added to the API in October 22 but had gone under my radar, it is in active development now.

**Comment by kalaiselvan162** [comment]
okay daniel

**Comment by danieldevine** [comment]
Direct Messaging functionality is now added from v0.6.0. documentation is available on the docs site.

**Comment by kalaiselvan162** [comment]
thank you daniel!
