### ISSUE TITLE
Decide whether to use signed requests based on the token, not the endpoint

### ISSUE THREAD

**Issue by shaneiseminger** [danieldevine/bird-elephant#57]
**Describe the bug**

In `Coderjerk\BirdElephant\Request::authorisedRequest()` the code decides whether to use 2.0 or 1.0a-basd authentication by the `$signed` property, which is passed along with each specific endpoint call. The problem this introduces is that it will try to use 2.0 token-based authentication even when you pass a 1.0a token/secret.

**To Reproduce**
```
$be = new BirdElephant([
    'consumer_key' => [...],
    'consumer_secret' => [...],
    'token_identifier' => [...],
    'token_secret' => [...],
]);

$be->user('shaneiseminger')->tweets();
```

This produces a 401 Unauthorized error. In debugging, I can see that an empty `Authorization` header is passed instead of the OAuth1 headers.

```
Authorization: Bearer
```

**Expected behavior**

I would expect the library to decide the authorization style based on the tokens passed in the constructor, as tokens and authentication methods are not interchangeable.

Most 2.0 endpoints support 1.0a tokens, so it's not necessary to force a certain authentication style for certain endpoints. It would be totally fair to throw an exception if 1.0a tokens are used for an endpoint that does not support it. 

Happy to provide a PR if you like.

**Environment (please complete the following information):**
 - Operating System: Debian
 - php version: 7.4
 - Bird Elephant version: 0.6.1

**Comment by danieldevine** [comment]
@shaneiseminger thanks for the detailed issue report. I'm considering the overall architecture at the moment for an upcoming version 1.0 and this is relevant. I have very little time to dedicate to the project in the meantime so happy to look at a PR if you want to submit one.
