### ISSUE TITLE
Allow passing user ID in BirdElephant constructor

### ISSUE THREAD

**Issue by shaneiseminger** [danieldevine/bird-elephant#58]
**Is your feature request related to a problem? Please describe.**

The library automatically fetches the user ID for a given username, which slows things down and burns an extra request. And when I do things like this:

```
$be->user('shaneiseminger')->tweets();
```

it actually fires _two_ successive requests for the user ID:

1. `Coderjerk\BirdElephant\User` instantiates several classes in the constructor.
2. One of them,`Coderjerk\BirdElephant\Users\Bookmarks` fetches the user ID in the constructor.
3. Then `Coderjerk\BirdElephant\Tweets` fetches it again for the `tweets()` method.

**Describe the solution you'd like**

I think it's common to store user metadata with an access token. We certainly do. So it would be helpful to avoid those extra requests and by passing the user ID like so:

```
$be->user('shaneiseminger', 12345)->tweets();
```

You would need to solve the duplicate-request bug, because it stems from the fact that individual classes do not share user IDs, therefore each has to retrieve it separately. For the above solution to work, there would need to be some kind of common storage.

**Describe alternatives you've considered**

The simplest would be to pass the user ID as a third argument to the constructor of each class that requires a username, though that doesn't allow us to fetch it on-demand and still share it with all other classes. So I suggest:

1. A separate class that does user ID lookups
2. Said class also caches results in a static var
3. Every class that needs the user ID then just instantiates that class

```
class UserIdLookup extends ApiBase {

    private static array $userIdCache = [];

    public function __invoke(string $username) 
    {
        if (empty(self::$userIdCache[$username]) {
             self::$userIdCache[$username] = $this->getUserId($username);
        }
        return self::$userIdCache[$username];
    }

}
```
Usage:
```
      $userIdLookup = new UserIdLookup('screenname');
      $userId = $userIdLookup();
```

Happy to submit a PR.

**Comment by danieldevine** [comment]
Response to #57 applies here too, thanks.

**Comment by danieldevine** [comment]
Thanks for the contributions @shaneiseminger
