### ISSUE TITLE
Async media upload status check keeps refreshing

### ISSUE THREAD

**Issue by rubanaan** [danieldevine/bird-elephant#62]
At this moment the `sleep()` methods on the `uploadMedia()` function gets a `null` argument, so it keeps refreshing. This is because the `check_after_secs` parameter has to be in the `processing_info` object.

https://github.com/danieldevine/bird-elephant/blob/cff000ff5b348d23d449288c6eaca5c5e701b696/src/Request.php#L245

I think it should work if you change this line to:

```php
sleep($status->processing_info->check_after_secs);
```

**Comment by bmartus** [comment]
FWIW, I ran into this error and trying with the change @rubanaan suggests seems to have fixed it.

**Comment by danieldevine** [comment]
thanks for the report, appreciate it.
